description: Sweep for training 

# Training script to run
program: main.py

# Method can be bayes, random, grid
method: grid

# Parameters to search over
parameters:
  algorithm:
   value: "PerAvgHFOneStep"
  dataset:
   value: "prep_FederatedEMNIST"
  model:
   value: "cnn"
  batch_size:
   value: 32
  num_global_iters:
   value: 402
  local_epochs:
   value: 20
  optimizer:
   value: "SGD"
  numusers:
   value: 20
  seed:
   values: [1, 2, 3, 4, 5]
  
  personal_epochs:
   values: [1]
  decimate:
   value: 50
  
  beta:
   values: [0.1] #hyperparameters taken from peravgHF 10 epoch personalization # 
  
  #PerAvg, PerAvgHF, pFedMe
  learning_rate: 
   values: [0.01]

  #ridge
  # user_ridge_penalty:
  #  values: [0.01, 1, 10]

  #HF
  delta_HF:
   values: [0.00001]

  #pFedMe
  # lambda:
  #  values: []
  # personal_learning_rate:
  #  values: []
  # K:
  #  values: []


  #misc
  times:
   value: 1
  rank:
   value: 0
  

  
  # dropout1:
  #  values:
  # dropout2:
  #  values:

